### PR TITLE
fix(parsers): Harmonisation des parseurs URSSAF (suite)

### PR DESCRIPTION
**Pull request by adrienjoly**
Contribue à #167.

## Changements apportés

Dans parseurs URSSAF restants:

- Suite de PR #174: extraction de `parseXxxFile()` et `parseXxxLine()` 
- Suite de PR #198: usage d'un `map` `colMapping` pour stocker les indices de colonnes
- Suite de PR #193: compter aussi les lignes où une erreur de parsing a été rencontrée

### CODE REVIEW

**Comment by adrienjoly** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity decreasing per file
==============================
+ dbmongo/lib/urssaf/cotisation.go  -3
+ dbmongo/lib/urssaf/ccsf.go  -5
+ dbmongo/lib/urssaf/effectif_ent.go  -7
+ dbmongo/lib/urssaf/delai.go  -2
         

Clones added
============
- dbmongo/lib/urssaf/cotisation.go  1
         

Clones removed
==============
+ dbmongo/lib/urssaf/effectif_ent.go  -1
+ dbmongo/lib/urssaf/delai.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6339255&bid=20592330)

**Comment by adrienjoly** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity decreasing per file
==============================
+ dbmongo/lib/urssaf/ccsf.go  -5
+ dbmongo/lib/urssaf/cotisation.go  -3
+ dbmongo/lib/urssaf/effectif_ent.go  -6
+ dbmongo/lib/urssaf/delai.go  -2
         

Clones added
============
- dbmongo/lib/urssaf/cotisation.go  1
         

Clones removed
==============
+ dbmongo/lib/urssaf/effectif_ent.go  -1
+ dbmongo/lib/urssaf/delai.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6339255&bid=20592330)

**Comment by adrienjoly** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity decreasing per file
==============================
+ dbmongo/lib/urssaf/cotisation.go  -3
+ dbmongo/lib/urssaf/effectif_ent.go  -9
+ dbmongo/lib/urssaf/ccsf.go  -5
+ dbmongo/lib/urssaf/delai.go  -2
         

Clones added
============
- dbmongo/lib/urssaf/cotisation.go  1
         

Clones removed
==============
+ dbmongo/lib/urssaf/delai.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6339255&bid=20592330)

**Comment by adrienjoly** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity decreasing per file
==============================
+ dbmongo/lib/urssaf/cotisation.go  -3
+ dbmongo/lib/urssaf/delai.go  -2
+ dbmongo/lib/urssaf/ccsf.go  -5
+ dbmongo/lib/urssaf/effectif_ent.go  -9
         

Clones added
============
- dbmongo/lib/urssaf/cotisation.go  1
         

Clones removed
==============
+ dbmongo/lib/urssaf/delai.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6339255&bid=20592330)

**Comment by adrienjoly** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity decreasing per file
==============================
+ dbmongo/lib/urssaf/ccsf.go  -5
+ dbmongo/lib/urssaf/delai.go  -2
+ dbmongo/lib/urssaf/effectif_ent.go  -9
+ dbmongo/lib/urssaf/cotisation.go  -3
+ dbmongo/lib/urssaf/effectif.go  -2
         

Clones added
============
- dbmongo/lib/urssaf/cotisation.go  1
         

Clones removed
==============
+ dbmongo/lib/urssaf/delai.go  -1
+ dbmongo/lib/urssaf/effectif.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6339255&bid=20592330)

**Comment by adrienjoly** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity decreasing per file
==============================
+ dbmongo/lib/urssaf/cotisation.go  -3
+ dbmongo/lib/urssaf/effectif_ent.go  -9
+ dbmongo/lib/urssaf/ccsf.go  -5
+ dbmongo/lib/urssaf/effectif.go  -7
+ dbmongo/lib/urssaf/delai.go  -2
         

Clones added
============
- dbmongo/lib/urssaf/cotisation.go  1
         

Clones removed
==============
+ dbmongo/lib/urssaf/delai.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6339255&bid=20592330)

**Comment by adrienjoly** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity decreasing per file
==============================
+ dbmongo/lib/urssaf/effectif_ent.go  -9
+ dbmongo/lib/urssaf/delai.go  -2
+ dbmongo/lib/urssaf/ccsf.go  -5
+ dbmongo/lib/urssaf/procol.go  -2
+ dbmongo/lib/urssaf/effectif.go  -10
+ dbmongo/lib/urssaf/cotisation.go  -3
         

Clones added
============
- dbmongo/lib/urssaf/cotisation.go  1
         

Clones removed
==============
+ dbmongo/lib/urssaf/delai.go  -1
+ dbmongo/lib/urssaf/procol.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6339255&bid=20592330)

**Comment by adrienjoly** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity decreasing per file
==============================
+ dbmongo/lib/urssaf/delai.go  -2
+ dbmongo/lib/urssaf/procol.go  -2
+ dbmongo/lib/urssaf/ccsf.go  -5
+ dbmongo/lib/urssaf/effectif_ent.go  -9
+ dbmongo/lib/urssaf/cotisation.go  -3
+ dbmongo/lib/urssaf/effectif.go  -10
         

Clones added
============
- dbmongo/lib/urssaf/cotisation.go  1
         

Clones removed
==============
+ dbmongo/lib/urssaf/delai.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6339255&bid=20592330)

**Comment by adrienjoly** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity decreasing per file
==============================
+ dbmongo/lib/urssaf/ccsf.go  -5
+ dbmongo/lib/urssaf/delai.go  -2
+ dbmongo/lib/urssaf/effectif.go  -10
+ dbmongo/lib/urssaf/cotisation.go  -3
+ dbmongo/lib/urssaf/effectif_ent.go  -9
+ dbmongo/lib/urssaf/procol.go  -2
         

Clones added
============
- dbmongo/lib/urssaf/cotisation.go  1
         

Clones removed
==============
+ dbmongo/lib/urssaf/delai.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6339255&bid=20592330)

**Review by JazzyPierrot — APPROVED** [review]

**Pull request merged**
