### PR TITLE
fix(db): Éviter le underscore final dans le nom de collection Features_

### PR DESCRIPTION
**Pull request by adrienjoly**
...et créer un index quelque soit le nom de la collection.

### CODE REVIEW

**Comment by adrienjoly** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- dbmongo/lib/engine/reduce.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6371989&bid=20676634)

**Comment by adrienjoly** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- dbmongo/lib/engine/reduce.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6371989&bid=20676634)

**Comment by adrienjoly** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- dbmongo/lib/engine/reduce.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6371989&bid=20676634)

**Review by chrnin — APPROVED** [review]
Simple et efficace.
LGTM

**Pull request merged**
