### PR TITLE
fix(filter): Retrait de IsFiltered() => validation siret/siren déléguée à l'appelant

### PR DESCRIPTION
**Pull request by adrienjoly**
Suite de #222.

Next:
- Appliquer `SirenFilter` sur les tuples retournés par tous les parseurs, à un seul endroit.

### CODE REVIEW

**Comment by adrienjoly** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- dbmongo/lib/ellisphere/main.go  1
- dbmongo/lib/reporder/reporder.go  2
- dbmongo/lib/urssaf/effectif_ent.go  1
- dbmongo/lib/bdf/main.go  1
- dbmongo/lib/sirene_ul/main.go  1
         

Complexity decreasing per file
==============================
+ dbmongo/lib/marshal/mapping.go  -1
         

Clones added
============
- dbmongo/lib/sirene/main.go  1
- dbmongo/lib/sirene_ul/main.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6407844&bid=20768287)

**Comment by adrienjoly** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- dbmongo/lib/reporder/reporder.go  1
         

Complexity decreasing per file
==============================
+ dbmongo/lib/marshal/mapping.go  -2
         

Clones added
============
- dbmongo/lib/sirene/main.go  1
- dbmongo/lib/sirene_ul/main.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6407844&bid=20768287)

**Comment by adrienjoly** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- dbmongo/lib/reporder/reporder.go  1
         

Complexity decreasing per file
==============================
+ dbmongo/lib/marshal/mapping.go  -2
         

Clones added
============
- dbmongo/lib/sirene_ul/main.go  1
- dbmongo/lib/sirene/main.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6407844&bid=20768287)

**Comment by adrienjoly** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- dbmongo/lib/reporder/reporder.go  1
         

Complexity decreasing per file
==============================
+ dbmongo/lib/marshal/mapping.go  -2
         

Clones added
============
- dbmongo/lib/sirene/main.go  1
- dbmongo/lib/sirene_ul/main.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6407844&bid=20768287)

**Review by chrnin — APPROVED** [review]
LGTM

**Pull request merged**
